name: cinema_app
description: Il cinema a portata di mano
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: _shared/

  flutter_localizations:
    sdk: flutter
  
  shared_preferences: ^0.5.7
  dynamic_theme: ^1.0.1
  url_launcher: ^5.4.2
  barcode_flutter: ^1.1.2
  flip_card: ^0.4.4
  cupertino_icons: ^0.1.2
  outline_material_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/posters/
    - images/social/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
