name: cinema_app
description: Il cinema a portata di mano
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: _shared/

  flutter_localizations:
    sdk: flutter

  # Google services
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.0.8

  # Icons
  cupertino_icons: ^0.1.2
  outline_material_icons: ^0.1.0
  font_awesome_flutter: ^8.8.1

  # Other
  email_validator: ^1.0.4
  shared_preferences: ^0.5.7
  dynamic_theme: ^1.0.1
  url_launcher: ^5.4.5
  barcode_flutter: ^1.1.2
  flip_card: ^0.4.4
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
